### ISSUE TITLE
Missing file from documentation in AWS QuickStart

### ISSUE THREAD

**Issue by Areso** [planetscale/vitess-operator#382] opened 2023-02-13 14:51 UTC
In the document https://github.com/planetscale/vitess-operator/blob/main/docs/aws-quickstart.md there are few mentions of  `exampledb_aws.yaml` , but if you clone the repo and try to find it, you will not find the file.
`find . -name "exampledb_aws.yaml"`
returns nothing in the repo

**Comment by frouioui** [comment] 2024-12-03 19:56
Duplicate of https://github.com/planetscale/vitess-operator/issues/310

**Closed by frouioui** 2024-12-03 19:56 UTC
