### ISSUE TITLE
Ready for production?

### ISSUE THREAD

**Issue by fzyzcjy** [planetscale/vitess-operator#182] opened 2021-04-02 03:04 UTC
Hi thanks for the lib! I wonder whether this operator is ready for production?

**Comment by prime-minister-of-fun** [comment] 2021-05-20 14:48
No it is not.  Among other things, there is only one user defined and that user has root access.

**Comment by fzyzcjy** [comment] 2021-05-22 09:29
Ah :/ Thanks!

**Comment by frouioui** [comment] 2024-04-30 20:17
Duplicate of https://github.com/planetscale/vitess-operator/issues/394, closing this issue for now.

**Closed by frouioui** 2024-04-30 20:17 UTC
